export const data = {
  products: [
    {
      id: 1,
      name: "Products with long name",
      image: "../../asset/image/product.jpg",
      originPrice: "45,000",
      promotionPrice: "40,000",
      promotion: 20,
    },
    {
      id: 2,
      name: "Products with long name",
      image: "/image/product.jpg",
      originPrice: "45,000",
      promotionPrice: "40,000",
      promotion: 20,
    },
    {
      id: 3,
      name: "Products with long name",
      image: "/image/product.jpg",
      originPrice: "45,000",
      promotionPrice: "40,000",
      promotion: 20,
    },
    {
      id: 4,
      name: "Products with long name",
      originPrice: "45,000",
      promotionPrice: "40,000",
      image: "/image/product.jpg",
      promotion: 10,
    },
    {
      id: 5,
      name: "Products with long name",
      image: "/image/product.jpg",
      originPrice: "45,000",
      promotionPrice: "40,000",
      promotion: 20,
    },
    {
      id: 6,
      name: "Products with long name",
      image: "/image/product.jpg",
      originPrice: "45,000",
      promotionPrice: "40,000",
      promotion: 20,
    },
    {
      id: 7,
      name: "Products with long name",
      image: "/image/product.jpg",
      originPrice: "45,000",
      promotionPrice: "40,000",
      promotion: 20,
    },
    {
      id: 8,
      name: "Products with long name",
      image: "/image/product.jpg",
      originPrice: "45,000",
      promotionPrice: "40,000",
      promotion: 20,
    },
    {
      id: 9,
      name: "Products with long name",
      image: "/image/product.jpg",
      originPrice: "45,000",
      promotionPrice: "40,000",
      promotion: 20,
    },
    {
      id: 10,
      name: "Products with long name",
      image: "/image/product.jpg",
      originPrice: "45,000",
      promotionPrice: "40,000",
      promotion: 20,
    },
  ],
  categories: [
    {
      id: 1,
      name: "category name",
      image: "/image/category/phone.png",
    },
    {
      id: 2,
      name: "category name",
      image: "/image/category/tablet.png",
    },
    {
      id: 3,
      name: "category name",
      image: "/image/category/laptop.png",
    },
    {
      id: 4,
      name: "category name",
      image: "/image/category/watch.png",
    },
    {
      id: 5,
      name: "category name",
      image: "/image/category/medicine.png",
    },
    {
      id: 6,
      name: "category name",
      image: "/image/category/laptop.png",
    },
    {
      id: 7,
      name: "category name",
      image: "/image/category/laptop.png",
    },
    {
      id: 8,
      name: "category name",
      image: "/image/category/laptop.png",
    },
    {
      id: 9,
      name: "category name",
      image: "/image/category/laptop.png",
    },
    {
      id: 10,
      name: "category name",
      image: "/image/category/laptop.png",
    },
    {
      id: 11,
      name: "category name",
      image: "/image/category/laptop.png",
    },
    {
      id: 12,
      name: "category name",
      image: "/image/category/laptop.png",
    },
    {
      id: 13,
      name: "category name",
      image: "/image/category/laptop.png",
    },
    {
      id: 14,
      name: "category name",
      image: "/image/category/laptop.png",
    },
  ],
  brands: [
    {
      id: 1,
      name: "apple",
      image: "/image/brands/apple.png",
    },
    {
      id: 2,
      name: "samsaung",
      image: "/image/brands/samsaung.png",
    },
    {
      id: 3,
      name: "google",
      image: "/image/brands/google.png",
    },
    {
      id: 4,
      name: "one-plus",
      image: "/image/brands/one-plus.png",
    },
    {
      id: 5,
      name: "mi",
      image: "/image/brands/mi.png",
    },
    {
      id: 6,
      name: "realme",
      image: "/image/brands/realme.png",
    },
    {
      id: 7,
      name: "huawei",
      image: "/image/brands/huawei.png",
    },
    {
      id: 8,
      name: "google",
      image: "/image/brands/google.png",
    },
    {
      id: 9,
      name: "google",
      image: "/image/brands/google.png",
    },
  ],
};
